apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
    component: zipkin
spec:
  type: NodePort
  ports:
  - name: http
    port: 9411
  selector:
    app: zipkin
    component: zipkin
