== Demo - Simple Hello Spring Boot/Kubernetes app deployment

. Create a simple Boot app
+
----
curl https://start.spring.io/starter.zip -d bootVersion=1.5.6.RELEASE \
     -d dependencies=web,actuator \
     -d groupId=com.springdeveloper.k8s -d artifactId=hello \
     -d name=hello -d baseDir=hello -o hello.zip
unzip hello.zip
cd hello
----

. Add a `@RestController` and a mapping for `/hello` (the bold parts are the additions):
+
.HelloApplication.java
[source,subs=+quotes]
----
package com.springdeveloper.k8s.hello;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
*import org.springframework.web.bind.annotation.GetMapping;*
*import org.springframework.web.bind.annotation.RestController;*

@SpringBootApplication
public class HelloApplication {
	public static void main(String[] args) {
		SpringApplication.run(HelloApplication.class, args);
	}

	*@RestController*
	*class HelloController {*
		*@GetMapping("/hello")*
		*String hello() {*
			*return "Hello Kubernauts!";*
		*}*
	*}*
}
----

. Add a property disabling security for the `env` endpoint so we can inspect environment variables added by Kubernetes 
+
.application.properties
----
endpoints.env.sensitive=false
----

. Create a `Dockerfile` so we can package this app as a Docker image
+
.Dockerfile
----
FROM java:8-alpine
VOLUME /tmp
ADD ./target/hello-*.jar /hello.jar
RUN sh -c 'touch /hello.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/hello.jar"]
----

. Build the app and the Docker image 
+
(we are assuming that you have a DockerHub account matching your username here, if that is not the case adjust accordingly)
+
----
./mvnw clean package
docker build -t $USER/hello .
----

. Test Docker container locally
+
----
docker run -p 8080:8080 $USER/hello
curl http://localhost:8080/hello
----

. Push Docker container to a new registry for your DockerHub account
+
----
docker push $USER/hello
----
+
NOTE: You can share the Docker environment with Minikube by issuing an `eval $(minikube docker-env)` command. That way when you build the Docker image it will be available to Minikube and you don't have to push it to DockerHub.
+
. Run a Kubernetes deployment on the running Minikube cluster
+
----
kubectl run hello --image trisberg/hello --port=8080
kubectl expose deployment hello --type=NodePort
minikube service hello --url
----

. Test the app
+
----
curl $(minikube service hello --url)/hello
----

. Inspect environment variables and Kubernetes deployment/service yaml
+
----
curl $(minikube service hello --url)/env | python -m json.tool
kubectl get deploy/hello -o yaml
kubectl get svc/hello -o yaml
----

. Delete the resources created for `hello`
+
----
kubectl delete all -l run=hello
----
