== Demo - Simple REST Repository App

===== Create the app and the config for local testing

. Create a small CRUD JPA Repository app
+
----
curl https://start.spring.io/starter.zip -d bootVersion=1.5.6.RELEASE \
    -d dependencies=web,actuator,jpa,data-rest,mysql,hsql \
    -d groupId=com.springdeveloper.k8s -d artifactId=actors \
    -d name=actors -d baseDir=actors -o actors.zip
unzip actors.zip
cd actors
----

. Add an Actor Entity
+
.Actor.java
[source,java]
----
package com.springdeveloper.k8s.actors;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Actor {

	@Id
	@GeneratedValue
	Long id;

	String name;

	int age;

	public Long getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}
}
----

. Add an ActorRepository
+
.ActorRepository.java
[source,java]
----
package com.springdeveloper.k8s.actors;

import java.util.List;

import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;

public interface ActorRepository extends PagingAndSortingRepository<Actor, Long> {

	List<Actor> findByName(@Param("name") String name);

}
----

. Create default properties file for running app locally
+
.application-default.properties
[source,props]
----
endpoints.env.sensitive=false
spring.datasource.url=jdbc:hsqldb:file:target/testdb
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=create
spring.datasource.initialize=true
----

. Build and run the app locally
+
----
./mvnw clean package
java -jar target/actors-0.0.1-SNAPSHOT.jar
----

. You can add actor records:
+
----
curl -i -X POST -H "Content-Type:application/json" -d "{  \"name\" : \"Dolph Lundgren\",  \"age\" : 59 }" http://localhost:8080/actors
----

. Test
+
----
curl http://localhost:8080/actors | python -m json.tool
----

===== Add Kubernetes configuration

. Add config properties for running on Kubernetes
+
We'll use standalone MySQL database that we'll configure later
+
.application-kubernetes.properties
[source,props]
----
endpoints.env.sensitive=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialize=false
----

. Add `assembly.xml` and Docker Maven plug-in to the `pom.xml`
+
.src/main/docker/assembly.xml
[source,xml]
----
<assembly
        xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2
            http://maven.apache.org/xsd/assembly-1.1.2.xsd">
    <id>actors</id>
    <dependencySets>
        <dependencySet>
            <includes>
                <include>com.springdeveloper.k8s:actors</include>
            </includes>
            <outputDirectory>.</outputDirectory>
            <outputFileNameMapping>actors.jar</outputFileNameMapping>
        </dependencySet>
    </dependencySets>
</assembly>
----
+
.pom.xml
[source,xml]
----
...
	<build>
		<plugins>
...
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.21.0</version>
				<configuration>
					<images>
						<image>
							<name>actors</name>
							<build>
								<from>java:8-alpine</from>
								<volumes>
									<volume>/tmp</volume>
								</volumes>
								<entryPoint>
									<exec>
										<arg>java</arg>
										<arg>-jar</arg>
										<arg>/maven/actors.jar</arg>
									</exec>
								</entryPoint>
								<assembly>
									<descriptor>assembly.xml</descriptor>
								</assembly>
							</build>
						</image>
					</images>
				</configuration>
			</plugin>
		</plugins>
	</build>
...
----

. Add Spring Cloud Kubernetes Starter (originally Fabric8, now spring-cloud-incubator project)
+
.pom.xml
[source,xml]
----
...
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-kubernetes-config</artifactId>
			<version>0.2.0.RELEASE</version>
		</dependency>
...
----

. Create the Kubernetes configuration files for the app
+
.config/actors-svc.yaml
[source,yaml]
----
kind: Service
apiVersion: v1
metadata:
  name: actors
  labels:
    app: actors
spec:
  # If you are running k8s on a local dev box or using minikube, you can use type NodePort instead of LoadBalancer
  type: NodePort
  ports:
    - port: 80
  selector:
    app: actors
----
+
.config/actors-deployment.yaml
[source,yaml]
----
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: actors
  labels:
    app: actors
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: actors
    spec:
      containers:
      - name: actors
        image: trisberg/actors:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1.0
            memory: 1024Mi
          requests:
            cpu: 0.5
            memory: 640Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name: SERVER_PORT
          value: '80'
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
          value: 'true'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_NAME
          value: mysql
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
          value: actors
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: 'false'
----
+
.config/actors-config.yaml
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: actors
  labels:
    app: actors
data:
  application.yaml: |-
    security:
      basic:
        enabled: false
    spring:
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${mysql-root-password}
        driverClassName: com.mysql.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"
----
+
. Configure a MySQL deployment and service
+
.mysql/mysql-deployment.yaml
[source,yaml]
----
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            # You can change this password - if you do change the base64 encoded value in the secrets file
            value: yourpassword
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql
----
+
.mysql/mysql-svc.yaml
[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
----
+
.mysql/mysql-pvc.yaml
[source,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
----
+
.mysql/mysql-secrets.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app: mysql
data:
  mysql-root-password: eW91cnBhc3N3b3Jk
----

===== Deploy database and app to Kubernetes and test

. Create a MySQL deployment and service
+
----
kubectl apply -f ./mysql/
----

. Build app and push Docker image
+
----
./mvnw clean package docker:build
docker tag actors $USER/actors:0.0.1
docker push $USER/actors:0.0.1
----

. Deploy app to k8s
+
----
kubectl apply -f config/
----

. Get status
+
----
$ kubectl get all
NAME                         READY     STATUS    RESTARTS   AGE
po/actors-2063423708-g81sz   1/1       Running   0          2h
po/mysql-777890292-ht5v2     1/1       Running   0          13h

NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
svc/actors       10.0.0.185   <nodes>       80:31012/TCP   2h
svc/kubernetes   10.0.0.1     <none>        443/TCP        13h
svc/mysql        10.0.0.83    <none>        3306/TCP       13h

NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/actors   1         1         1            1           2h
deploy/mysql    1         1         1            1           13h

NAME                   DESIRED   CURRENT   READY     AGE
rs/actors-2063423708   1         1         1         2h
rs/mysql-777890292     1         1         1         13h
----

. Add some actor records (empty table in database initially):
+
We need a shell script to look up the IP address of the server and then POST some data to it
+
./data/add-actors.sh
[source,bash]
----
ACTORS_URL="$(minikube service actors --url)"
echo "POSTing data to $ACTORS_URL"
curl -i -X POST -H "Content-Type:application/json" -d "{  \"name\" : \"Jack Nicholson\",  \"age\" : 80 }" $ACTORS_URL/actors
curl -i -X POST -H "Content-Type:application/json" -d "{  \"name\" : \"Al Pacino\",  \"age\" : 77 }" $ACTORS_URL/actors
curl -i -X POST -H "Content-Type:application/json" -d "{  \"name\" : \"Meryl Streep\",  \"age\" : 68 }" $ACTORS_URL/actors
curl -i -X POST -H "Content-Type:application/json" -d "{  \"name\" : \"Jennifer Lawrence\",  \"age\" : 26 }" $ACTORS_URL/actors
curl -i -X POST -H "Content-Type:application/json" -d "{  \"name\" : \"Julia Roberts\",  \"age\" : 49 }" $ACTORS_URL/actors
curl -i -X POST -H "Content-Type:application/json" -d "{  \"name\" : \"Bradley Cooper\",  \"age\" : 42 }" $ACTORS_URL/actors
----
+
----
./data/add-actors.sh
----
