apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: metrics
    component: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    name: grafana
  selector:
    app: metrics
    component: grafana
