apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: metrics
    component: grafana
spec:
  replicas: 1
  template:
    metadata:
      annotations:
          alpha.istio.io/sidecar: "ignore"
      labels:
        app: metrics
        component: grafana
    spec:
      containers:
      - name: grafana
        image:  "grafana/grafana:4.4.1"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
        - name: GRAFANA_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_PATHS_DATA
          value: /data/grafana
        volumeMounts:
        - mountPath: /data/grafana
          name: grafana-data
      volumes:
      - name: grafana-data
        emptyDir: {}
