apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: metrics
    component: prometheus
  annotations:
      prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
  selector:
    app: metrics
    component: prometheus
