apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: metrics
    component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
      component: prometheus
  template:
    metadata:
      annotations:
          alpha.istio.io/sidecar: "ignore"
      name: prometheus
      labels:
        app: metrics
        component: prometheus
    spec:
      containers:
      - name: prometheus
        image: "prom/prometheus:v1.7.1"
        imagePullPolicy: IfNotPresent
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: web
          containerPort: 9090
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
