kind: Service
apiVersion: v1
metadata:
  name: actors
  labels:
    app: actors
spec:
  # If you are running k8s on a local dev box or using minikube, you can use type NodePort instead of LoadBalancer
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: actors
