kind: Service
apiVersion: v1
metadata:
  name: images
  labels:
    app: images
spec:
  # If you are running k8s on a local dev box or using minikube, you can use type NodePort instead of LoadBalancer
  type: NodePort
  ports:
    - port: 80
  selector:
    app: images
